#!/bin/bash
VARIANT=${1}

if [ $# -gt 1 ]
then
    FILES="magic/${VARIANT}/${2}.mag"
    echo "Extracting 1 layout: $FILES"
else
    FILES=$(ls magic/${VARIANT}/*.mag)
    echo "Extracting VARIANT (${VARIANT}) layouts: $FILES"
fi

for i in ${FILES}; do
    sed -i 's/rlabel polycont\|rlabel poly\|rlabel viali\|rlabel nsubdiffcont\|rlabel psubdiffcont/rlabel locali/g' $i
    sed -i 's/rlabel locali/rlabel metal1/g' $i
    sed -i '/^port.*$/d' $i
    sed -i '/rlabel.*/a port SEDTMP n' $i
    sed -i '/vdd$/{$!{N;s/vdd\nport.*/vdd/g;tl;P;D;:l}}' $i
    sed -i '/gnd$/{$!{N;s/gnd\nport.*/gnd/g;tl;P;D;:l}}' $i
    sed -i -r ':a;/SEDTMP/{x;:b;s/9(_*)$/_\1/;tb;s/^(_*)$/0\1/;s/$/:0123456789/;s/([^_])(_*):.*\1(.).*/\3\2/;s/_/0/g;x;G;s/SEDTMP(.*)\n(.*)/\2\1/;ta}' $i
    sed -i 's/\(^.*locali\|^.*metal1\|^.*cont\|^.*viali\) \(.* gnd\|.* vdd$\)/rlabel locali \2/g' $i
    awk '!(seen[$0]++ && (/gnd/ || /vdd/))' $i > tmp.sim && mv tmp.sim $i
    echo "source scripts/magic_extract.tcl" | magic -dnull -noconsole $i
    #sed -i 's/\(^.*locali\|^.*metal1\|^.*cont\|^.*viali\) \(.* gnd\|.* vdd$\)/rlabel metal1 \2/g' $i
    #echo "source scripts/magic_calma.tcl;calma" | magic -dnull -noconsole $i
done

